// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  collapsible: dynamic(() => import("./Collapsible")),
  embed: dynamic(() => import("./Embed")),
  hero_slider: dynamic(() => import("./HeroSlider")),
  image: dynamic(() => import("./Images")),
  image_links: dynamic(() => import("./ImageLinks")),
  rich_text: dynamic(() => import("./IntroText")),
};
